name: 'Revert Sponsor Label Changes' 
description: 'Reverts label changes made by members of a specified sponsor team' 
inputs:
  github-token: 
    description: 'GitHub token with required permissions'
    required: true
  sponsor-team-slug:
    description: 'The slug of your sponsor team'
    required: true
  allowed-labels: 
    description: 'Comma-separated list of labels allowed for the sponsor team'
    required: true 
runs:
  using: 'node20'
  main: 'index.js'